// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, balance, currency_id) 
VALUES ($1, $2, $3, $4) 
RETURNING id, user_id, name, balance, currency_id
`

type CreateAccountParams struct {
	UserID     pgtype.Int4   `json:"user_id"`
	Name       string        `json:"name"`
	Balance    pgtype.Float8 `json:"balance"`
	CurrencyID pgtype.Int4   `json:"currency_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Balance,
		arg.CurrencyID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Balance,
		&i.CurrencyID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, balance, currency_id FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Balance,
		&i.CurrencyID,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, name, balance, currency_id FROM accounts WHERE user_id = $1
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID pgtype.Int4) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Balance,
			&i.CurrencyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET name = $1, balance = $2, currency_id = $3
WHERE id = $4
`

type UpdateAccountParams struct {
	Name       string        `json:"name"`
	Balance    pgtype.Float8 `json:"balance"`
	CurrencyID pgtype.Int4   `json:"currency_id"`
	ID         int32         `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.Name,
		arg.Balance,
		arg.CurrencyID,
		arg.ID,
	)
	return err
}
