// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: currency.sql

package sqlc

import (
	"context"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currency (name, conversion_rate) 
VALUES ($1, $2) 
RETURNING id, name, conversion_rate
`

type CreateCurrencyParams struct {
	Name           string  `json:"name"`
	ConversionRate float64 `json:"conversion_rate"`
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, createCurrency, arg.Name, arg.ConversionRate)
	var i Currency
	err := row.Scan(&i.ID, &i.Name, &i.ConversionRate)
	return i, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
DELETE FROM currency WHERE id = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCurrency, id)
	return err
}

const getCurrencyByID = `-- name: GetCurrencyByID :one
SELECT id, name, conversion_rate FROM currency WHERE id = $1
`

func (q *Queries) GetCurrencyByID(ctx context.Context, id int32) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrencyByID, id)
	var i Currency
	err := row.Scan(&i.ID, &i.Name, &i.ConversionRate)
	return i, err
}

const getCurrencyByName = `-- name: GetCurrencyByName :one
SELECT id, name, conversion_rate FROM currency WHERE name = $1
`

func (q *Queries) GetCurrencyByName(ctx context.Context, name string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrencyByName, name)
	var i Currency
	err := row.Scan(&i.ID, &i.Name, &i.ConversionRate)
	return i, err
}

const updateCurrency = `-- name: UpdateCurrency :exec
UPDATE currency
SET name = $1, conversion_rate = $2
WHERE id = $3
`

type UpdateCurrencyParams struct {
	Name           string  `json:"name"`
	ConversionRate float64 `json:"conversion_rate"`
	ID             int32   `json:"id"`
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) error {
	_, err := q.db.Exec(ctx, updateCurrency, arg.Name, arg.ConversionRate, arg.ID)
	return err
}
