// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: expense_categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (user_id, name) 
VALUES ($1, $2) 
RETURNING id, user_id, name
`

type CreateExpenseCategoryParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.UserID, arg.Name)
	var i ExpenseCategory
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories WHERE id = $1
`

func (q *Queries) DeleteExpenseCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, id)
	return err
}

const getExpenseCategoriesByUserID = `-- name: GetExpenseCategoriesByUserID :many
SELECT id, user_id, name FROM expense_categories WHERE user_id = $1
`

func (q *Queries) GetExpenseCategoriesByUserID(ctx context.Context, userID pgtype.Int4) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, getExpenseCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseCategoryByID = `-- name: GetExpenseCategoryByID :one
SELECT id, user_id, name FROM expense_categories WHERE id = $1
`

func (q *Queries) GetExpenseCategoryByID(ctx context.Context, id int32) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByID, id)
	var i ExpenseCategory
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :exec
UPDATE expense_categories
SET name = $1
WHERE id = $2
`

type UpdateExpenseCategoryParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) error {
	_, err := q.db.Exec(ctx, updateExpenseCategory, arg.Name, arg.ID)
	return err
}
