// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: expense_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseRecord = `-- name: CreateExpenseRecord :one
INSERT INTO expense_records (
    user_id, account_id, title, category_id, amount, attachment
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, account_id, title, category_id, amount, attachment
`

type CreateExpenseRecordParams struct {
	UserID     pgtype.Int4 `json:"user_id"`
	AccountID  pgtype.Int4 `json:"account_id"`
	Title      string      `json:"title"`
	CategoryID pgtype.Int4 `json:"category_id"`
	Amount     float64     `json:"amount"`
	Attachment pgtype.Text `json:"attachment"`
}

func (q *Queries) CreateExpenseRecord(ctx context.Context, arg CreateExpenseRecordParams) (ExpenseRecord, error) {
	row := q.db.QueryRow(ctx, createExpenseRecord,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.CategoryID,
		arg.Amount,
		arg.Attachment,
	)
	var i ExpenseRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.CategoryID,
		&i.Amount,
		&i.Attachment,
	)
	return i, err
}

const deleteExpenseRecord = `-- name: DeleteExpenseRecord :exec
DELETE FROM expense_records WHERE id = $1
`

func (q *Queries) DeleteExpenseRecord(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteExpenseRecord, id)
	return err
}

const deleteExpenseRecordsByAccount = `-- name: DeleteExpenseRecordsByAccount :exec
DELETE FROM expense_records WHERE account_id = $1
`

func (q *Queries) DeleteExpenseRecordsByAccount(ctx context.Context, accountID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteExpenseRecordsByAccount, accountID)
	return err
}

const deleteExpenseRecordsByCategory = `-- name: DeleteExpenseRecordsByCategory :exec
DELETE FROM expense_records WHERE category_id = $1
`

func (q *Queries) DeleteExpenseRecordsByCategory(ctx context.Context, categoryID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteExpenseRecordsByCategory, categoryID)
	return err
}

const deleteExpenseRecordsByUser = `-- name: DeleteExpenseRecordsByUser :exec
DELETE FROM expense_records WHERE user_id = $1
`

func (q *Queries) DeleteExpenseRecordsByUser(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteExpenseRecordsByUser, userID)
	return err
}

const getExpenseRecordByID = `-- name: GetExpenseRecordByID :one
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM expense_records WHERE id = $1
`

func (q *Queries) GetExpenseRecordByID(ctx context.Context, id int32) (ExpenseRecord, error) {
	row := q.db.QueryRow(ctx, getExpenseRecordByID, id)
	var i ExpenseRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.CategoryID,
		&i.Amount,
		&i.Attachment,
	)
	return i, err
}

const listExpenseRecordsByAccount = `-- name: ListExpenseRecordsByAccount :many
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM expense_records WHERE account_id = $1 ORDER BY id DESC
`

func (q *Queries) ListExpenseRecordsByAccount(ctx context.Context, accountID pgtype.Int4) ([]ExpenseRecord, error) {
	rows, err := q.db.Query(ctx, listExpenseRecordsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseRecord
	for rows.Next() {
		var i ExpenseRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.CategoryID,
			&i.Amount,
			&i.Attachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseRecordsByCategory = `-- name: ListExpenseRecordsByCategory :many
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM expense_records WHERE category_id = $1 ORDER BY id DESC
`

func (q *Queries) ListExpenseRecordsByCategory(ctx context.Context, categoryID pgtype.Int4) ([]ExpenseRecord, error) {
	rows, err := q.db.Query(ctx, listExpenseRecordsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseRecord
	for rows.Next() {
		var i ExpenseRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.CategoryID,
			&i.Amount,
			&i.Attachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseRecordsByUser = `-- name: ListExpenseRecordsByUser :many
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM expense_records WHERE user_id = $1 ORDER BY id DESC
`

func (q *Queries) ListExpenseRecordsByUser(ctx context.Context, userID pgtype.Int4) ([]ExpenseRecord, error) {
	rows, err := q.db.Query(ctx, listExpenseRecordsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseRecord
	for rows.Next() {
		var i ExpenseRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.CategoryID,
			&i.Amount,
			&i.Attachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseRecord = `-- name: UpdateExpenseRecord :exec
UPDATE expense_records
SET
    user_id = $1,
    account_id = $2,
    title = $3,
    category_id = $4,
    amount = $5,
    attachment = $6
WHERE id = $7
`

type UpdateExpenseRecordParams struct {
	UserID     pgtype.Int4 `json:"user_id"`
	AccountID  pgtype.Int4 `json:"account_id"`
	Title      string      `json:"title"`
	CategoryID pgtype.Int4 `json:"category_id"`
	Amount     float64     `json:"amount"`
	Attachment pgtype.Text `json:"attachment"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateExpenseRecord(ctx context.Context, arg UpdateExpenseRecordParams) error {
	_, err := q.db.Exec(ctx, updateExpenseRecord,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.CategoryID,
		arg.Amount,
		arg.Attachment,
		arg.ID,
	)
	return err
}
