// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: income_categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncomeCategory = `-- name: CreateIncomeCategory :one
INSERT INTO income_categories (user_id, name) 
VALUES ($1, $2) 
RETURNING id, user_id, name
`

type CreateIncomeCategoryParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateIncomeCategory(ctx context.Context, arg CreateIncomeCategoryParams) (IncomeCategory, error) {
	row := q.db.QueryRow(ctx, createIncomeCategory, arg.UserID, arg.Name)
	var i IncomeCategory
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteIncomeCategory = `-- name: DeleteIncomeCategory :exec
DELETE FROM income_categories WHERE id = $1
`

func (q *Queries) DeleteIncomeCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIncomeCategory, id)
	return err
}

const getIncomeCategoriesByUserID = `-- name: GetIncomeCategoriesByUserID :many
SELECT id, user_id, name FROM income_categories WHERE user_id = $1
`

func (q *Queries) GetIncomeCategoriesByUserID(ctx context.Context, userID pgtype.Int4) ([]IncomeCategory, error) {
	rows, err := q.db.Query(ctx, getIncomeCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeCategory
	for rows.Next() {
		var i IncomeCategory
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomeCategoryByID = `-- name: GetIncomeCategoryByID :one
SELECT id, user_id, name FROM income_categories WHERE id = $1
`

func (q *Queries) GetIncomeCategoryByID(ctx context.Context, id int32) (IncomeCategory, error) {
	row := q.db.QueryRow(ctx, getIncomeCategoryByID, id)
	var i IncomeCategory
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const updateIncomeCategory = `-- name: UpdateIncomeCategory :exec
UPDATE income_categories
SET name = $1
WHERE id = $2
`

type UpdateIncomeCategoryParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateIncomeCategory(ctx context.Context, arg UpdateIncomeCategoryParams) error {
	_, err := q.db.Exec(ctx, updateIncomeCategory, arg.Name, arg.ID)
	return err
}
