// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: income_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncomeRecord = `-- name: CreateIncomeRecord :one
INSERT INTO income_records (
    user_id, account_id, title, category_id, amount, attachment
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, account_id, title, category_id, amount, attachment
`

type CreateIncomeRecordParams struct {
	UserID     pgtype.Int4 `json:"user_id"`
	AccountID  pgtype.Int4 `json:"account_id"`
	Title      string      `json:"title"`
	CategoryID pgtype.Int4 `json:"category_id"`
	Amount     float64     `json:"amount"`
	Attachment pgtype.Text `json:"attachment"`
}

func (q *Queries) CreateIncomeRecord(ctx context.Context, arg CreateIncomeRecordParams) (IncomeRecord, error) {
	row := q.db.QueryRow(ctx, createIncomeRecord,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.CategoryID,
		arg.Amount,
		arg.Attachment,
	)
	var i IncomeRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.CategoryID,
		&i.Amount,
		&i.Attachment,
	)
	return i, err
}

const deleteIncomeRecord = `-- name: DeleteIncomeRecord :exec
DELETE FROM income_records WHERE id = $1
`

func (q *Queries) DeleteIncomeRecord(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIncomeRecord, id)
	return err
}

const deleteIncomeRecordsByAccount = `-- name: DeleteIncomeRecordsByAccount :exec
DELETE FROM income_records WHERE account_id = $1
`

func (q *Queries) DeleteIncomeRecordsByAccount(ctx context.Context, accountID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteIncomeRecordsByAccount, accountID)
	return err
}

const deleteIncomeRecordsByCategory = `-- name: DeleteIncomeRecordsByCategory :exec
DELETE FROM income_records WHERE category_id = $1
`

func (q *Queries) DeleteIncomeRecordsByCategory(ctx context.Context, categoryID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteIncomeRecordsByCategory, categoryID)
	return err
}

const deleteIncomeRecordsByUser = `-- name: DeleteIncomeRecordsByUser :exec
DELETE FROM income_records WHERE user_id = $1
`

func (q *Queries) DeleteIncomeRecordsByUser(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteIncomeRecordsByUser, userID)
	return err
}

const getIncomeRecordByID = `-- name: GetIncomeRecordByID :one
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM income_records WHERE id = $1
`

func (q *Queries) GetIncomeRecordByID(ctx context.Context, id int32) (IncomeRecord, error) {
	row := q.db.QueryRow(ctx, getIncomeRecordByID, id)
	var i IncomeRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.CategoryID,
		&i.Amount,
		&i.Attachment,
	)
	return i, err
}

const listIncomeRecordsByAccount = `-- name: ListIncomeRecordsByAccount :many
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM income_records WHERE account_id = $1 ORDER BY id DESC
`

func (q *Queries) ListIncomeRecordsByAccount(ctx context.Context, accountID pgtype.Int4) ([]IncomeRecord, error) {
	rows, err := q.db.Query(ctx, listIncomeRecordsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeRecord
	for rows.Next() {
		var i IncomeRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.CategoryID,
			&i.Amount,
			&i.Attachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeRecordsByCategory = `-- name: ListIncomeRecordsByCategory :many
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM income_records WHERE category_id = $1 ORDER BY id DESC
`

func (q *Queries) ListIncomeRecordsByCategory(ctx context.Context, categoryID pgtype.Int4) ([]IncomeRecord, error) {
	rows, err := q.db.Query(ctx, listIncomeRecordsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeRecord
	for rows.Next() {
		var i IncomeRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.CategoryID,
			&i.Amount,
			&i.Attachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeRecordsByUser = `-- name: ListIncomeRecordsByUser :many
SELECT id, user_id, account_id, title, category_id, amount, attachment FROM income_records WHERE user_id = $1 ORDER BY id DESC
`

func (q *Queries) ListIncomeRecordsByUser(ctx context.Context, userID pgtype.Int4) ([]IncomeRecord, error) {
	rows, err := q.db.Query(ctx, listIncomeRecordsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeRecord
	for rows.Next() {
		var i IncomeRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.CategoryID,
			&i.Amount,
			&i.Attachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncomeRecord = `-- name: UpdateIncomeRecord :exec
UPDATE income_records
SET
    user_id = $1,
    account_id = $2,
    title = $3,
    category_id = $4,
    amount = $5,
    attachment = $6
WHERE id = $7
`

type UpdateIncomeRecordParams struct {
	UserID     pgtype.Int4 `json:"user_id"`
	AccountID  pgtype.Int4 `json:"account_id"`
	Title      string      `json:"title"`
	CategoryID pgtype.Int4 `json:"category_id"`
	Amount     float64     `json:"amount"`
	Attachment pgtype.Text `json:"attachment"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateIncomeRecord(ctx context.Context, arg UpdateIncomeRecordParams) error {
	_, err := q.db.Exec(ctx, updateIncomeRecord,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.CategoryID,
		arg.Amount,
		arg.Attachment,
		arg.ID,
	)
	return err
}
