// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: installments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallment = `-- name: CreateInstallment :one
INSERT INTO installments (
    user_id, account_id, loan_id, title, amount, date, scheduled_record_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, account_id, loan_id, title, amount, date, scheduled_record_id
`

type CreateInstallmentParams struct {
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	LoanID            pgtype.Int4      `json:"loan_id"`
	Title             string           `json:"title"`
	Amount            float64          `json:"amount"`
	Date              pgtype.Timestamp `json:"date"`
	ScheduledRecordID pgtype.Int4      `json:"scheduled_record_id"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.UserID,
		arg.AccountID,
		arg.LoanID,
		arg.Title,
		arg.Amount,
		arg.Date,
		arg.ScheduledRecordID,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.LoanID,
		&i.Title,
		&i.Amount,
		&i.Date,
		&i.ScheduledRecordID,
	)
	return i, err
}

const deleteInstallment = `-- name: DeleteInstallment :exec
DELETE FROM installments WHERE id = $1
`

func (q *Queries) DeleteInstallment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInstallment, id)
	return err
}

const deleteInstallmentsByAccount = `-- name: DeleteInstallmentsByAccount :exec
DELETE FROM installments WHERE account_id = $1
`

func (q *Queries) DeleteInstallmentsByAccount(ctx context.Context, accountID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInstallmentsByAccount, accountID)
	return err
}

const deleteInstallmentsByLoan = `-- name: DeleteInstallmentsByLoan :exec
DELETE FROM installments WHERE loan_id = $1
`

func (q *Queries) DeleteInstallmentsByLoan(ctx context.Context, loanID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInstallmentsByLoan, loanID)
	return err
}

const deleteInstallmentsByScheduledRecord = `-- name: DeleteInstallmentsByScheduledRecord :exec
DELETE FROM installments WHERE scheduled_record_id = $1
`

func (q *Queries) DeleteInstallmentsByScheduledRecord(ctx context.Context, scheduledRecordID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInstallmentsByScheduledRecord, scheduledRecordID)
	return err
}

const deleteInstallmentsByUser = `-- name: DeleteInstallmentsByUser :exec
DELETE FROM installments WHERE user_id = $1
`

func (q *Queries) DeleteInstallmentsByUser(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInstallmentsByUser, userID)
	return err
}

const getInstallmentByID = `-- name: GetInstallmentByID :one
SELECT id, user_id, account_id, loan_id, title, amount, date, scheduled_record_id FROM installments WHERE id = $1
`

func (q *Queries) GetInstallmentByID(ctx context.Context, id int32) (Installment, error) {
	row := q.db.QueryRow(ctx, getInstallmentByID, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.LoanID,
		&i.Title,
		&i.Amount,
		&i.Date,
		&i.ScheduledRecordID,
	)
	return i, err
}

const listInstallmentsByAccount = `-- name: ListInstallmentsByAccount :many
SELECT id, user_id, account_id, loan_id, title, amount, date, scheduled_record_id FROM installments WHERE account_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInstallmentsByAccount(ctx context.Context, accountID pgtype.Int4) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.LoanID,
			&i.Title,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsByLoan = `-- name: ListInstallmentsByLoan :many
SELECT id, user_id, account_id, loan_id, title, amount, date, scheduled_record_id FROM installments WHERE loan_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInstallmentsByLoan(ctx context.Context, loanID pgtype.Int4) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByLoan, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.LoanID,
			&i.Title,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsByScheduledRecord = `-- name: ListInstallmentsByScheduledRecord :many
SELECT id, user_id, account_id, loan_id, title, amount, date, scheduled_record_id FROM installments WHERE scheduled_record_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInstallmentsByScheduledRecord(ctx context.Context, scheduledRecordID pgtype.Int4) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByScheduledRecord, scheduledRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.LoanID,
			&i.Title,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsByUser = `-- name: ListInstallmentsByUser :many
SELECT id, user_id, account_id, loan_id, title, amount, date, scheduled_record_id FROM installments WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInstallmentsByUser(ctx context.Context, userID pgtype.Int4) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.LoanID,
			&i.Title,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallment = `-- name: UpdateInstallment :exec
UPDATE installments
SET
    user_id = $1,
    account_id = $2,
    loan_id = $3,
    title = $4,
    amount = $5,
    date = $6,
    scheduled_record_id = $7
WHERE id = $8
`

type UpdateInstallmentParams struct {
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	LoanID            pgtype.Int4      `json:"loan_id"`
	Title             string           `json:"title"`
	Amount            float64          `json:"amount"`
	Date              pgtype.Timestamp `json:"date"`
	ScheduledRecordID pgtype.Int4      `json:"scheduled_record_id"`
	ID                int32            `json:"id"`
}

func (q *Queries) UpdateInstallment(ctx context.Context, arg UpdateInstallmentParams) error {
	_, err := q.db.Exec(ctx, updateInstallment,
		arg.UserID,
		arg.AccountID,
		arg.LoanID,
		arg.Title,
		arg.Amount,
		arg.Date,
		arg.ScheduledRecordID,
		arg.ID,
	)
	return err
}
