// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: investments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (
    user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id
`

type CreateInvestmentParams struct {
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	Title             string           `json:"title"`
	InvestmentTypeID  pgtype.Int4      `json:"investment_type_id"`
	Amount            float64          `json:"amount"`
	Date              pgtype.Timestamp `json:"date"`
	ScheduledRecordID pgtype.Int4      `json:"scheduled_record_id"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.InvestmentTypeID,
		arg.Amount,
		arg.Date,
		arg.ScheduledRecordID,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.InvestmentTypeID,
		&i.Amount,
		&i.Date,
		&i.ScheduledRecordID,
	)
	return i, err
}

const deleteInvestment = `-- name: DeleteInvestment :exec
DELETE FROM investments WHERE id = $1
`

func (q *Queries) DeleteInvestment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInvestment, id)
	return err
}

const deleteInvestmentsByAccount = `-- name: DeleteInvestmentsByAccount :exec
DELETE FROM investments WHERE account_id = $1
`

func (q *Queries) DeleteInvestmentsByAccount(ctx context.Context, accountID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInvestmentsByAccount, accountID)
	return err
}

const deleteInvestmentsByScheduledRecord = `-- name: DeleteInvestmentsByScheduledRecord :exec
DELETE FROM investments WHERE scheduled_record_id = $1
`

func (q *Queries) DeleteInvestmentsByScheduledRecord(ctx context.Context, scheduledRecordID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInvestmentsByScheduledRecord, scheduledRecordID)
	return err
}

const deleteInvestmentsByType = `-- name: DeleteInvestmentsByType :exec
DELETE FROM investments WHERE investment_type_id = $1
`

func (q *Queries) DeleteInvestmentsByType(ctx context.Context, investmentTypeID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInvestmentsByType, investmentTypeID)
	return err
}

const deleteInvestmentsByUser = `-- name: DeleteInvestmentsByUser :exec
DELETE FROM investments WHERE user_id = $1
`

func (q *Queries) DeleteInvestmentsByUser(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteInvestmentsByUser, userID)
	return err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id FROM investments WHERE id = $1
`

func (q *Queries) GetInvestmentByID(ctx context.Context, id int32) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.InvestmentTypeID,
		&i.Amount,
		&i.Date,
		&i.ScheduledRecordID,
	)
	return i, err
}

const listInvestmentsByAccount = `-- name: ListInvestmentsByAccount :many
SELECT id, user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id FROM investments WHERE account_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInvestmentsByAccount(ctx context.Context, accountID pgtype.Int4) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.InvestmentTypeID,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByScheduledRecord = `-- name: ListInvestmentsByScheduledRecord :many
SELECT id, user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id FROM investments WHERE scheduled_record_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInvestmentsByScheduledRecord(ctx context.Context, scheduledRecordID pgtype.Int4) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByScheduledRecord, scheduledRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.InvestmentTypeID,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByType = `-- name: ListInvestmentsByType :many
SELECT id, user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id FROM investments WHERE investment_type_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInvestmentsByType(ctx context.Context, investmentTypeID pgtype.Int4) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByType, investmentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.InvestmentTypeID,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByUser = `-- name: ListInvestmentsByUser :many
SELECT id, user_id, account_id, title, investment_type_id, amount, date, scheduled_record_id FROM investments WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListInvestmentsByUser(ctx context.Context, userID pgtype.Int4) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.InvestmentTypeID,
			&i.Amount,
			&i.Date,
			&i.ScheduledRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvestment = `-- name: UpdateInvestment :exec
UPDATE investments
SET
    user_id = $1,
    account_id = $2,
    title = $3,
    investment_type_id = $4,
    amount = $5,
    date = $6,
    scheduled_record_id = $7
WHERE id = $8
`

type UpdateInvestmentParams struct {
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	Title             string           `json:"title"`
	InvestmentTypeID  pgtype.Int4      `json:"investment_type_id"`
	Amount            float64          `json:"amount"`
	Date              pgtype.Timestamp `json:"date"`
	ScheduledRecordID pgtype.Int4      `json:"scheduled_record_id"`
	ID                int32            `json:"id"`
}

func (q *Queries) UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) error {
	_, err := q.db.Exec(ctx, updateInvestment,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.InvestmentTypeID,
		arg.Amount,
		arg.Date,
		arg.ScheduledRecordID,
		arg.ID,
	)
	return err
}
