// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: investment_types.sql

package sqlc

import (
	"context"
)

const createInvestmentType = `-- name: CreateInvestmentType :one
INSERT INTO investment_types (user_id, name) 
VALUES ($1, $2) 
RETURNING id, user_id, name, created_at, modified_at
`

type CreateInvestmentTypeParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateInvestmentType(ctx context.Context, arg CreateInvestmentTypeParams) (InvestmentType, error) {
	row := q.db.QueryRow(ctx, createInvestmentType, arg.UserID, arg.Name)
	var i InvestmentType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteInvestmentType = `-- name: DeleteInvestmentType :exec
DELETE FROM investment_types WHERE id = $1
`

func (q *Queries) DeleteInvestmentType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInvestmentType, id)
	return err
}

const getInvestmentTypeByID = `-- name: GetInvestmentTypeByID :one
SELECT id, user_id, name, created_at, modified_at FROM investment_types WHERE id = $1
`

func (q *Queries) GetInvestmentTypeByID(ctx context.Context, id int32) (InvestmentType, error) {
	row := q.db.QueryRow(ctx, getInvestmentTypeByID, id)
	var i InvestmentType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getInvestmentTypesByUserID = `-- name: GetInvestmentTypesByUserID :many
SELECT id, user_id, name, created_at, modified_at FROM investment_types WHERE user_id = $1
`

func (q *Queries) GetInvestmentTypesByUserID(ctx context.Context, userID int32) ([]InvestmentType, error) {
	rows, err := q.db.Query(ctx, getInvestmentTypesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentType
	for rows.Next() {
		var i InvestmentType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvestmentType = `-- name: UpdateInvestmentType :exec
UPDATE investment_types
SET name = $1, modified_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateInvestmentTypeParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateInvestmentType(ctx context.Context, arg UpdateInvestmentTypeParams) error {
	_, err := q.db.Exec(ctx, updateInvestmentType, arg.Name, arg.ID)
	return err
}
