// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: loan_types.sql

package sqlc

import (
	"context"
)

const createLoanType = `-- name: CreateLoanType :one
INSERT INTO loan_types (user_id, name) 
VALUES ($1, $2) 
RETURNING id, user_id, name, created_at, modified_at
`

type CreateLoanTypeParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateLoanType(ctx context.Context, arg CreateLoanTypeParams) (LoanType, error) {
	row := q.db.QueryRow(ctx, createLoanType, arg.UserID, arg.Name)
	var i LoanType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteLoanType = `-- name: DeleteLoanType :exec
DELETE FROM loan_types WHERE id = $1
`

func (q *Queries) DeleteLoanType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLoanType, id)
	return err
}

const getLoanTypeByID = `-- name: GetLoanTypeByID :one
SELECT id, user_id, name, created_at, modified_at FROM loan_types WHERE id = $1
`

func (q *Queries) GetLoanTypeByID(ctx context.Context, id int32) (LoanType, error) {
	row := q.db.QueryRow(ctx, getLoanTypeByID, id)
	var i LoanType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getLoanTypesByUserID = `-- name: GetLoanTypesByUserID :many
SELECT id, user_id, name, created_at, modified_at FROM loan_types WHERE user_id = $1
`

func (q *Queries) GetLoanTypesByUserID(ctx context.Context, userID int32) ([]LoanType, error) {
	rows, err := q.db.Query(ctx, getLoanTypesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanType
	for rows.Next() {
		var i LoanType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoanType = `-- name: UpdateLoanType :exec
UPDATE loan_types
SET name = $1, modified_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateLoanTypeParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateLoanType(ctx context.Context, arg UpdateLoanTypeParams) error {
	_, err := q.db.Exec(ctx, updateLoanType, arg.Name, arg.ID)
	return err
}
