// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: loans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (
    user_id, account_id, title, loan_type_id, amount, date
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, account_id, title, loan_type_id, amount, date
`

type CreateLoanParams struct {
	UserID     pgtype.Int4      `json:"user_id"`
	AccountID  pgtype.Int4      `json:"account_id"`
	Title      string           `json:"title"`
	LoanTypeID pgtype.Int4      `json:"loan_type_id"`
	Amount     float64          `json:"amount"`
	Date       pgtype.Timestamp `json:"date"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.LoanTypeID,
		arg.Amount,
		arg.Date,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.LoanTypeID,
		&i.Amount,
		&i.Date,
	)
	return i, err
}

const deleteLoan = `-- name: DeleteLoan :exec
DELETE FROM loans WHERE id = $1
`

func (q *Queries) DeleteLoan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLoan, id)
	return err
}

const deleteLoansByAccount = `-- name: DeleteLoansByAccount :exec
DELETE FROM loans WHERE account_id = $1
`

func (q *Queries) DeleteLoansByAccount(ctx context.Context, accountID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteLoansByAccount, accountID)
	return err
}

const deleteLoansByType = `-- name: DeleteLoansByType :exec
DELETE FROM loans WHERE loan_type_id = $1
`

func (q *Queries) DeleteLoansByType(ctx context.Context, loanTypeID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteLoansByType, loanTypeID)
	return err
}

const deleteLoansByUser = `-- name: DeleteLoansByUser :exec
DELETE FROM loans WHERE user_id = $1
`

func (q *Queries) DeleteLoansByUser(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteLoansByUser, userID)
	return err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, user_id, account_id, title, loan_type_id, amount, date FROM loans WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int32) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.LoanTypeID,
		&i.Amount,
		&i.Date,
	)
	return i, err
}

const listLoansByAccount = `-- name: ListLoansByAccount :many
SELECT id, user_id, account_id, title, loan_type_id, amount, date FROM loans WHERE account_id = $1 ORDER BY date DESC
`

func (q *Queries) ListLoansByAccount(ctx context.Context, accountID pgtype.Int4) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.LoanTypeID,
			&i.Amount,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByType = `-- name: ListLoansByType :many
SELECT id, user_id, account_id, title, loan_type_id, amount, date FROM loans WHERE loan_type_id = $1 ORDER BY date DESC
`

func (q *Queries) ListLoansByType(ctx context.Context, loanTypeID pgtype.Int4) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByType, loanTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.LoanTypeID,
			&i.Amount,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByUser = `-- name: ListLoansByUser :many
SELECT id, user_id, account_id, title, loan_type_id, amount, date FROM loans WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListLoansByUser(ctx context.Context, userID pgtype.Int4) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.LoanTypeID,
			&i.Amount,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoan = `-- name: UpdateLoan :exec
UPDATE loans
SET
    user_id = $1,
    account_id = $2,
    title = $3,
    loan_type_id = $4,
    amount = $5,
    date = $6
WHERE id = $7
`

type UpdateLoanParams struct {
	UserID     pgtype.Int4      `json:"user_id"`
	AccountID  pgtype.Int4      `json:"account_id"`
	Title      string           `json:"title"`
	LoanTypeID pgtype.Int4      `json:"loan_type_id"`
	Amount     float64          `json:"amount"`
	Date       pgtype.Timestamp `json:"date"`
	ID         int32            `json:"id"`
}

func (q *Queries) UpdateLoan(ctx context.Context, arg UpdateLoanParams) error {
	_, err := q.db.Exec(ctx, updateLoan,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.LoanTypeID,
		arg.Amount,
		arg.Date,
		arg.ID,
	)
	return err
}
