// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID         int32         `json:"id"`
	UserID     pgtype.Int4   `json:"user_id"`
	Name       string        `json:"name"`
	Balance    pgtype.Float8 `json:"balance"`
	CurrencyID pgtype.Int4   `json:"currency_id"`
}

type Currency struct {
	ID             int32   `json:"id"`
	Name           string  `json:"name"`
	ConversionRate float64 `json:"conversion_rate"`
}

type ExpenseCategory struct {
	ID     int32       `json:"id"`
	UserID pgtype.Int4 `json:"user_id"`
	Name   string      `json:"name"`
}

type ExpenseRecord struct {
	ID         int32       `json:"id"`
	UserID     pgtype.Int4 `json:"user_id"`
	AccountID  pgtype.Int4 `json:"account_id"`
	Title      string      `json:"title"`
	CategoryID pgtype.Int4 `json:"category_id"`
	Amount     float64     `json:"amount"`
	Attachment pgtype.Text `json:"attachment"`
}

type IncomeCategory struct {
	ID     int32       `json:"id"`
	UserID pgtype.Int4 `json:"user_id"`
	Name   string      `json:"name"`
}

type IncomeRecord struct {
	ID         int32       `json:"id"`
	UserID     pgtype.Int4 `json:"user_id"`
	AccountID  pgtype.Int4 `json:"account_id"`
	Title      string      `json:"title"`
	CategoryID pgtype.Int4 `json:"category_id"`
	Amount     float64     `json:"amount"`
	Attachment pgtype.Text `json:"attachment"`
}

type Installment struct {
	ID                int32            `json:"id"`
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	LoanID            pgtype.Int4      `json:"loan_id"`
	Title             string           `json:"title"`
	Amount            float64          `json:"amount"`
	Date              pgtype.Timestamp `json:"date"`
	ScheduledRecordID pgtype.Int4      `json:"scheduled_record_id"`
}

type Investment struct {
	ID                int32            `json:"id"`
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	Title             string           `json:"title"`
	InvestmentTypeID  pgtype.Int4      `json:"investment_type_id"`
	Amount            float64          `json:"amount"`
	Date              pgtype.Timestamp `json:"date"`
	ScheduledRecordID pgtype.Int4      `json:"scheduled_record_id"`
}

type InvestmentType struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	Name       string           `json:"name"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ModifiedAt pgtype.Timestamp `json:"modified_at"`
}

type Loan struct {
	ID         int32            `json:"id"`
	UserID     pgtype.Int4      `json:"user_id"`
	AccountID  pgtype.Int4      `json:"account_id"`
	Title      string           `json:"title"`
	LoanTypeID pgtype.Int4      `json:"loan_type_id"`
	Amount     float64          `json:"amount"`
	Date       pgtype.Timestamp `json:"date"`
}

type LoanType struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	Name       string           `json:"name"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ModifiedAt pgtype.Timestamp `json:"modified_at"`
}

type ScheduledRecord struct {
	ID                int32            `json:"id"`
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	Title             string           `json:"title"`
	Type              pgtype.Text      `json:"type"`
	CategoryID        pgtype.Int4      `json:"category_id"`
	Amount            float64          `json:"amount"`
	Status            pgtype.Text      `json:"status"`
	Date              pgtype.Timestamp `json:"date"`
	RecurringInterval pgtype.Timestamp `json:"recurring_interval"`
	Recurring         pgtype.Bool      `json:"recurring"`
}

type User struct {
	ID         int32            `json:"id"`
	Name       pgtype.Text      `json:"name"`
	Email      string           `json:"email"`
	Password   string           `json:"password"`
	IsVerified bool             `json:"is_verified"`
	PhotoUrl   pgtype.Text      `json:"photo_url"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ModifiedAt pgtype.Timestamp `json:"modified_at"`
	LastActive pgtype.Timestamp `json:"last_active"`
}
