// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: scheduled_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduledRecord = `-- name: CreateScheduledRecord :one
INSERT INTO scheduled_records (
    user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring
`

type CreateScheduledRecordParams struct {
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	Title             string           `json:"title"`
	Type              pgtype.Text      `json:"type"`
	CategoryID        pgtype.Int4      `json:"category_id"`
	Amount            float64          `json:"amount"`
	Status            pgtype.Text      `json:"status"`
	Date              pgtype.Timestamp `json:"date"`
	RecurringInterval pgtype.Timestamp `json:"recurring_interval"`
	Recurring         pgtype.Bool      `json:"recurring"`
}

func (q *Queries) CreateScheduledRecord(ctx context.Context, arg CreateScheduledRecordParams) (ScheduledRecord, error) {
	row := q.db.QueryRow(ctx, createScheduledRecord,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.Type,
		arg.CategoryID,
		arg.Amount,
		arg.Status,
		arg.Date,
		arg.RecurringInterval,
		arg.Recurring,
	)
	var i ScheduledRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.Type,
		&i.CategoryID,
		&i.Amount,
		&i.Status,
		&i.Date,
		&i.RecurringInterval,
		&i.Recurring,
	)
	return i, err
}

const deleteScheduledRecord = `-- name: DeleteScheduledRecord :exec
DELETE FROM scheduled_records WHERE id = $1
`

func (q *Queries) DeleteScheduledRecord(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteScheduledRecord, id)
	return err
}

const deleteScheduledRecordsByAccount = `-- name: DeleteScheduledRecordsByAccount :exec
DELETE FROM scheduled_records WHERE account_id = $1
`

func (q *Queries) DeleteScheduledRecordsByAccount(ctx context.Context, accountID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteScheduledRecordsByAccount, accountID)
	return err
}

const deleteScheduledRecordsByStatus = `-- name: DeleteScheduledRecordsByStatus :exec
DELETE FROM scheduled_records WHERE status = $1
`

func (q *Queries) DeleteScheduledRecordsByStatus(ctx context.Context, status pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteScheduledRecordsByStatus, status)
	return err
}

const deleteScheduledRecordsByType = `-- name: DeleteScheduledRecordsByType :exec
DELETE FROM scheduled_records WHERE type = $1
`

func (q *Queries) DeleteScheduledRecordsByType(ctx context.Context, type_ pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteScheduledRecordsByType, type_)
	return err
}

const deleteScheduledRecordsByUser = `-- name: DeleteScheduledRecordsByUser :exec
DELETE FROM scheduled_records WHERE user_id = $1
`

func (q *Queries) DeleteScheduledRecordsByUser(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteScheduledRecordsByUser, userID)
	return err
}

const getScheduledRecordByID = `-- name: GetScheduledRecordByID :one
SELECT id, user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring FROM scheduled_records WHERE id = $1
`

func (q *Queries) GetScheduledRecordByID(ctx context.Context, id int32) (ScheduledRecord, error) {
	row := q.db.QueryRow(ctx, getScheduledRecordByID, id)
	var i ScheduledRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Title,
		&i.Type,
		&i.CategoryID,
		&i.Amount,
		&i.Status,
		&i.Date,
		&i.RecurringInterval,
		&i.Recurring,
	)
	return i, err
}

const listScheduledRecordsByAccount = `-- name: ListScheduledRecordsByAccount :many
SELECT id, user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring FROM scheduled_records WHERE account_id = $1 ORDER BY date DESC
`

func (q *Queries) ListScheduledRecordsByAccount(ctx context.Context, accountID pgtype.Int4) ([]ScheduledRecord, error) {
	rows, err := q.db.Query(ctx, listScheduledRecordsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRecord
	for rows.Next() {
		var i ScheduledRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.Type,
			&i.CategoryID,
			&i.Amount,
			&i.Status,
			&i.Date,
			&i.RecurringInterval,
			&i.Recurring,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRecordsByStatus = `-- name: ListScheduledRecordsByStatus :many
SELECT id, user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring FROM scheduled_records WHERE status = $1 ORDER BY date DESC
`

func (q *Queries) ListScheduledRecordsByStatus(ctx context.Context, status pgtype.Text) ([]ScheduledRecord, error) {
	rows, err := q.db.Query(ctx, listScheduledRecordsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRecord
	for rows.Next() {
		var i ScheduledRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.Type,
			&i.CategoryID,
			&i.Amount,
			&i.Status,
			&i.Date,
			&i.RecurringInterval,
			&i.Recurring,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRecordsByType = `-- name: ListScheduledRecordsByType :many
SELECT id, user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring FROM scheduled_records WHERE type = $1 ORDER BY date DESC
`

func (q *Queries) ListScheduledRecordsByType(ctx context.Context, type_ pgtype.Text) ([]ScheduledRecord, error) {
	rows, err := q.db.Query(ctx, listScheduledRecordsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRecord
	for rows.Next() {
		var i ScheduledRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.Type,
			&i.CategoryID,
			&i.Amount,
			&i.Status,
			&i.Date,
			&i.RecurringInterval,
			&i.Recurring,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRecordsByUser = `-- name: ListScheduledRecordsByUser :many
SELECT id, user_id, account_id, title, type, category_id, amount, status, date, recurring_interval, recurring FROM scheduled_records WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListScheduledRecordsByUser(ctx context.Context, userID pgtype.Int4) ([]ScheduledRecord, error) {
	rows, err := q.db.Query(ctx, listScheduledRecordsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRecord
	for rows.Next() {
		var i ScheduledRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Title,
			&i.Type,
			&i.CategoryID,
			&i.Amount,
			&i.Status,
			&i.Date,
			&i.RecurringInterval,
			&i.Recurring,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledRecord = `-- name: UpdateScheduledRecord :exec
UPDATE scheduled_records
SET
    user_id = $1,
    account_id = $2,
    title = $3,
    type = $4,
    category_id = $5,
    amount = $6,
    status = $7,
    date = $8,
    recurring_interval = $9,
    recurring = $10
WHERE id = $11
`

type UpdateScheduledRecordParams struct {
	UserID            pgtype.Int4      `json:"user_id"`
	AccountID         pgtype.Int4      `json:"account_id"`
	Title             string           `json:"title"`
	Type              pgtype.Text      `json:"type"`
	CategoryID        pgtype.Int4      `json:"category_id"`
	Amount            float64          `json:"amount"`
	Status            pgtype.Text      `json:"status"`
	Date              pgtype.Timestamp `json:"date"`
	RecurringInterval pgtype.Timestamp `json:"recurring_interval"`
	Recurring         pgtype.Bool      `json:"recurring"`
	ID                int32            `json:"id"`
}

func (q *Queries) UpdateScheduledRecord(ctx context.Context, arg UpdateScheduledRecordParams) error {
	_, err := q.db.Exec(ctx, updateScheduledRecord,
		arg.UserID,
		arg.AccountID,
		arg.Title,
		arg.Type,
		arg.CategoryID,
		arg.Amount,
		arg.Status,
		arg.Date,
		arg.RecurringInterval,
		arg.Recurring,
		arg.ID,
	)
	return err
}
