// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, email, password, is_verified, photo_url
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, email, password, is_verified, photo_url, created_at, modified_at, last_active
`

type CreateUserParams struct {
	Name       pgtype.Text `json:"name"`
	Email      string      `json:"email"`
	Password   string      `json:"password"`
	IsVerified bool        `json:"is_verified"`
	PhotoUrl   pgtype.Text `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.IsVerified,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerified,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.LastActive,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, is_verified, photo_url, created_at, modified_at, last_active FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerified,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.LastActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, is_verified, photo_url, created_at, modified_at, last_active FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerified,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.LastActive,
	)
	return i, err
}

const markUserAsVerified = `-- name: MarkUserAsVerified :exec
UPDATE users
SET is_verified = TRUE, modified_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserAsVerified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markUserAsVerified, id)
	return err
}

const updateLastActive = `-- name: UpdateLastActive :exec
UPDATE users
SET last_active = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastActive(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateLastActive, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    name = $1,
    email = $2,
    password = $3,
    is_verified = $4,
    photo_url = $5,
    modified_at = NOW()
WHERE id = $6
`

type UpdateUserParams struct {
	Name       pgtype.Text `json:"name"`
	Email      string      `json:"email"`
	Password   string      `json:"password"`
	IsVerified bool        `json:"is_verified"`
	PhotoUrl   pgtype.Text `json:"photo_url"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.IsVerified,
		arg.PhotoUrl,
		arg.ID,
	)
	return err
}
